### ISSUE TITLE
LEDs wrong behavior

### ISSUE THREAD

**Issue by TimFins** [jgarff/rpi_ws281x#481] opened 2021-12-09 10:02 UTC
Hello there,

I have the following problem: 
I try to make one ws2812 LED from adafruit work with this library via the SPI pin 10. Of course SPI is enabled and the CPU Freq and CPU min is set to the right value in the boot data. I use rapsberry pi 4 for this but the LEDs simply don't get the right colors. They are mostly white and won't turn off. I try the strandtest.py example for python. I also thought about DMA channels that are already in use and tried many of them but that doesn't work for me.  I tried the ones that shouldn't be used default but also can't really test this.
Furthermore I have the problem that the second LED won't do anything even when I change the LED count to 2. But that shouldn't be the first topic first.
I also send you a picture of my wiring but this shouldn't cause the problem...

Greetings and thanks a lot if you can help!!!
Tim
![Uploading IMG_20211209_110005.jpg…]()

**Comment by Gadgetoid** [comment] 2022-01-25 14:19
Dupe of #482 

Beep boop, I'm a robot, honest :robot:

**Closed by Gadgetoid** 2022-01-25 14:19 UTC
