### ISSUE TITLE
Sk6812 rgbw support ?

### ISSUE THREAD

**Issue by penfold42** [jgarff/rpi_ws281x#88] opened 2016-05-03 10:24 UTC
How hard is it to add support for these LEDs ?

Same bit signaling  protocol but 32bits of data not 24

**Comment by penfold42** [comment] 2016-05-03 11:51
Not very by the looks of it.

I've ordered some LEDs but will have to test with the scope while I'm waiting.

Is anyone in a position to test this on real LEDs in the mean time ?

**Comment by jgarff** [comment] 2016-05-30 16:44
Support has now been added, please use the sk6812 branch for testing.  I'm going to close this issue as a duplicate of #89.  Thanks.

**Closed by jgarff** 2016-05-30 16:44 UTC
